description = "cflinuxfs3 base image with buildpacks for Java, .NET, NodeJS, Golang, PHP, HTTPD and NGINX"

[[order]]
group = [

### Order is strictly enforced
  { id = "org.cloudfoundry.openjdk" },
  { id = "org.cloudfoundry.buildsystem",               optional = true },

### Order determines precedence
  { id = "org.cloudfoundry.jvmapplication" },
  { id = "org.cloudfoundry.tomcat",                    optional = true },
  { id = "org.cloudfoundry.springboot",                optional = true },
  { id = "org.cloudfoundry.distzip",                   optional = true },
  { id = "org.cloudfoundry.procfile",                  optional = true },

### Order does not matter
  { id = "org.cloudfoundry.azureapplicationinsights",  optional = true },
  { id = "org.cloudfoundry.debug",                     optional = true },
  { id = "org.cloudfoundry.googlestackdriver",         optional = true },
  { id = "org.cloudfoundry.jdbc",                      optional = true },
  { id = "org.cloudfoundry.jmx",                       optional = true },
  { id = "org.cloudfoundry.springautoreconfiguration", optional = true },
]

[[order]]
group = [
  { id = "org.cloudfoundry.nodejs" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.go" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.dotnet-core" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.php" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.httpd" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.nginx" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.procfile" },
]
