description = "cflinuxfs3 base image with buildpacks for Java, .NET, NodeJS, Golang, PHP, HTTPD and NGINX"

[[order]]
group = [

### Order is strictly enforced
  { id = "paketo-buildpacks/bellsoft-liberica",          optional = true },
  { id = "paketo-buildpacks/build-system",               optional = true },

### Order determines precedence
  { id = "paketo-buildpacks/executable-jar",             optional = true },
  { id = "paketo-buildpacks/apache-tomcat",              optional = true },
  { id = "paketo-buildpacks/spring-boot",                optional = true },
  { id = "paketo-buildpacks/dist-zip",                   optional = true },
  { id = "paketo-buildpacks/procfile",                   optional = true },

### Order does not matter
  { id = "paketo-buildpacks/azure-application-insights", optional = true },
  { id = "paketo-buildpacks/debug",                      optional = true },
  { id = "paketo-buildpacks/jmx",                        optional = true },

### Order is strictly enforced
  { id = "paketo-buildpacks/encrypt-at-rest",            optional = true },
]

[[order]]
group = [
  { id = "org.cloudfoundry.nodejs" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.go" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.dotnet-core" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.php" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.httpd" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.nginx" },
]

[[order]]
group = [
  { id = "org.cloudfoundry.procfile" },
]
